import { ArrowLeft, Mail, MessageCircle, Phone, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { SmartImage } from '../components/SmartImage';
import { emailUrl, smsUrl, whatsappUrl, type AppPage } from '../config/business';
import { constructionCategories } from '../finalData';
import type { ConstructionProduct } from '../types';

function productMessage(product: ConstructionProduct) {
  return `Guten Tag, ich interessiere mich für ${product.name}${product.pack ? ` (${product.pack})` : ''}. Bitte senden Sie mir Informationen und eine projektbezogene Offerte.`;
}

export function ConstructionPage({ hasProduct, onToggle, onNavigate }: { hasProduct: (product: ConstructionProduct) => boolean; onToggle: (product: ConstructionProduct) => void; onNavigate: (page: AppPage) => void }) {
  const [selected, setSelected] = useState<ConstructionProduct | null>(null);
  return <main className="bg-[#f3f5f6]">
    <section className="border-b border-[#d9e1e5] bg-white"><div className="mx-auto grid max-w-[1540px] gap-9 px-5 py-12 lg:grid-cols-[.88fr_1.12fr] lg:px-10 lg:py-16"><div className="self-center"><button onClick={() => onNavigate('products')} className="mb-6 inline-flex min-h-11 items-center gap-2 text-xs font-bold text-[#5a7180] hover:text-[#004b87]"><ArrowLeft size={15} /> Alle Sparten</button><p className="text-[11px] font-extrabold uppercase tracking-[.22em] text-[#9a6e22]">Sparte 01 · Reale Produktfotografie</p><h1 className="mt-4 font-display text-5xl font-bold leading-[1.02] tracking-[-.04em] text-[#10293e] lg:text-6xl">Baustellenzubehör ohne künstliche Baustellenszene</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#566e7d]">Die Hauptdarstellung zeigt das reale Produktset. Varianten, Packungseinheiten und technische Anwendung bleiben klar sichtbar.</p></div><div className="min-h-[410px] overflow-hidden rounded-[22px] border border-[#d8e1e6] bg-white"><SmartImage asset={{ src: '/images/Komplettset.png', alt: 'Reales Komplettset aus Nivellierclips und wiederverwendbaren Keilen', fit: 'contain' }} priority className="h-full w-full p-12" /></div></div></section>
    <div className="mx-auto max-w-[1540px] space-y-16 px-5 py-14 lg:px-10 lg:py-20">{constructionCategories.map((category) => <section key={category.title}><div className="mb-8 grid overflow-hidden rounded-[20px] border border-[#d7e0e5] bg-white md:grid-cols-[360px_1fr]"><div className="min-h-[220px] overflow-hidden bg-white"><SmartImage asset={{ src: category.products[0]?.image || '/images/Komplettset.png', alt: category.title, fit: 'contain' }} className="h-full w-full p-8" /></div><div className="self-center p-7 sm:p-9"><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-[#9a6e22]">Produktgruppe</p><h2 className="mt-2 font-display text-4xl font-bold tracking-[-.035em] text-[#10293e]">{category.title}</h2><p className="mt-4 max-w-3xl leading-7 text-[#5b7180]">{category.description}</p><p className="mt-4 text-xs font-bold text-[#004b87]">{category.products.length} konkrete Produkte</p></div></div><div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{category.products.map((product) => <ConstructionCard key={product.id} product={product} selected={hasProduct(product)} onDetails={() => setSelected(product)} onToggle={() => onToggle(product)} />)}</div></section>)}</div>
    {selected && <ConstructionModal product={selected} selected={hasProduct(selected)} onToggle={() => onToggle(selected)} onClose={() => setSelected(null)} />}
  </main>;
}

function ConstructionCard({ product, selected, onDetails, onToggle }: { product: ConstructionProduct; selected: boolean; onDetails: () => void; onToggle: () => void }) {
  const message = productMessage(product);
  return <article className="group flex flex-col overflow-hidden rounded-[20px] border border-[#d7e0e5] bg-white shadow-[0_10px_32px_rgba(16,41,62,.05)]"><button onClick={onDetails} className="relative aspect-[4/3] overflow-hidden border-b border-[#e0e6e9] bg-white"><SmartImage asset={{ src: product.image, alt: product.name, fit: 'contain' }} className="h-full w-full p-8 transition duration-700 group-hover:scale-[1.035]" />{product.badges?.length ? <div className="absolute left-4 top-4 flex flex-wrap gap-2">{product.badges.slice(0, 2).map((badge) => <span key={badge} className="rounded-full bg-[#eef4f7] px-3 py-1.5 text-[9px] font-extrabold uppercase tracking-[.12em] text-[#004b87]">{badge}</span>)}</div> : null}</button><div className="flex flex-1 flex-col p-6"><p className="text-[10px] font-extrabold uppercase tracking-[.17em] text-[#8e6725]">RA Bau Sortiment</p><button onClick={onDetails} className="mt-2 text-left"><h3 className="font-display text-2xl font-bold leading-tight tracking-[-.025em] text-[#10293e]">{product.name}</h3></button><p className="mt-3 text-sm leading-6 text-[#637987]">{product.description}</p><div className="mt-5 space-y-2 text-xs text-[#506a79]"><p><strong>Varianten:</strong> {product.variants}</p><p><strong>Packung:</strong> {product.pack}</p></div><div className="mt-auto flex gap-2 pt-6"><button onClick={onDetails} className="flex-1 rounded-lg border border-[#ccd7de] px-4 py-3 text-xs font-extrabold text-[#004b87]">Details</button><button onClick={onToggle} className={`flex-1 rounded-lg px-4 py-3 text-xs font-extrabold ${selected ? 'bg-[#fff0ee] text-[#9b3f3b]' : 'bg-[#004b87] text-white'}`}>{selected ? 'Entfernen' : 'Zur Offerte'}</button></div><div className="mt-2 grid grid-cols-3 gap-2"><a href={whatsappUrl(message)} target="_blank" rel="noreferrer" className="flex items-center justify-center gap-1 rounded-lg border border-[#d6e0e5] px-2 py-2 text-[10px] font-bold text-[#16734b]"><MessageCircle size={13} /> WhatsApp</a><a href={emailUrl(`Anfrage: ${product.name}`, message)} className="flex items-center justify-center gap-1 rounded-lg border border-[#d6e0e5] px-2 py-2 text-[10px] font-bold text-[#004b87]"><Mail size={13} /> E-Mail</a><a href={smsUrl(message)} className="flex items-center justify-center gap-1 rounded-lg border border-[#d6e0e5] px-2 py-2 text-[10px] font-bold text-[#4d6575]"><Phone size={13} /> SMS</a></div></div></article>;
}

function ConstructionModal({ product, selected, onToggle, onClose }: { product: ConstructionProduct; selected: boolean; onToggle: () => void; onClose: () => void }) {
  useEffect(() => { document.body.style.overflow = 'hidden'; const onKey = (event: KeyboardEvent) => event.key === 'Escape' && onClose(); window.addEventListener('keydown', onKey); return () => { document.body.style.overflow = ''; window.removeEventListener('keydown', onKey); }; }, [onClose]);
  const message = productMessage(product);
  return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-[#071925]/75 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label={product.name} onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="max-h-[92vh] w-full max-w-4xl overflow-auto rounded-[24px] bg-white shadow-2xl"><div className="sticky top-0 z-10 flex justify-end bg-white/90 p-3 backdrop-blur"><button onClick={onClose} className="rounded-full bg-[#eef2f4] p-2" aria-label="Schliessen"><X /></button></div><div className="grid lg:grid-cols-2"><div className="min-h-[430px] bg-white"><SmartImage asset={{ src: product.image, alt: product.name, fit: 'contain' }} priority className="h-full w-full p-12" /></div><div className="p-7 sm:p-10"><p className="text-[10px] font-extrabold uppercase tracking-[.18em] text-[#8e6725]">RA Bau Sortiment</p><h2 className="mt-2 font-display text-4xl font-bold tracking-[-.035em] text-[#10293e]">{product.name}</h2><p className="mt-5 leading-7 text-[#637987]">{product.description}</p><div className="mt-7 space-y-4 rounded-xl bg-[#f2f5f6] p-5 text-sm text-[#526b7a]"><p><strong>Anwendung:</strong> {product.application}</p><p><strong>Varianten:</strong> {product.variants}</p><p><strong>Packung:</strong> {product.pack}</p></div><button onClick={onToggle} className={`mt-7 w-full rounded-lg px-5 py-4 text-sm font-extrabold ${selected ? 'bg-[#fff0ee] text-[#9b3f3b]' : 'bg-[#004b87] text-white'}`}>{selected ? 'Aus Anfrage entfernen' : 'Zur gemeinsamen Offerte hinzufügen'}</button><div className="mt-3 grid grid-cols-3 gap-2"><a href={whatsappUrl(message)} target="_blank" rel="noreferrer" className="flex items-center justify-center gap-1 rounded-lg bg-[#16845a] px-2 py-3 text-[10px] font-extrabold text-white"><MessageCircle size={14} /> WhatsApp</a><a href={emailUrl(`Anfrage: ${product.name}`, message)} className="flex items-center justify-center gap-1 rounded-lg border border-[#cbd7de] px-2 py-3 text-[10px] font-extrabold text-[#004b87]"><Mail size={14} /> E-Mail</a><a href={smsUrl(message)} className="flex items-center justify-center gap-1 rounded-lg border border-[#cbd7de] px-2 py-3 text-[10px] font-extrabold text-[#415b6d]"><Phone size={14} /> SMS</a></div></div></div></div></div>;
}
