import { ArrowRight } from 'lucide-react';
import type { AppPage } from '../config/business';
import { ProcessSteps } from '../components/ProcessSteps';
import { SmartImage } from '../components/SmartImage';

const areas: Array<{ page: AppPage; number: string; title: string; copy: string; image: string; alt: string }> = [
  { page: 'construction', number: '01', title: 'Baustellenzubehör', copy: 'Nivelliersysteme, Abstandhalter, Drahtbinder, Schutzteile und Werkzeug.', image: '/images/Komplettset.png', alt: 'Nivelliersystem mit Clips und Keilen' },
  { page: 'ceramics', number: '02', title: 'Keramik & Feinsteinzeug', copy: 'Travertin, Marmor, Naturstein, Carving und mineralische Oberflächen.', image: '/images/catalog/recer-mastery.png', alt: 'Recer Mastery Keramik' },
  { page: 'bathroom', number: '03', title: 'Badezimmer', copy: 'Badmöbel, Armaturen, Duschsysteme, WC und Duschwannen.', image: '/images/catalog/rubicer-stria.png', alt: 'Rubicer Stria Badezimmermöbel' },
  { page: 'flooring', number: '04', title: 'Vinyl, SPC & Kork', copy: 'Fischgrat, XL-Dielen, helle Eiche, Projektqualität und Steinoptik.', image: '/images/products/rubifloor-herringbone-natural.webp', alt: 'Rubifloor Herringbone Natural Boden' },
  { page: 'concepts', number: '05', title: 'Raumkonzepte', copy: 'Fünf gekennzeichnete Visualisierungen mit konfigurierbaren Komponenten.', image: '/images/concepts/warm-stone-spa.svg', alt: 'Warm Stone Spa Raumkonzept Visualisierung' },
];

export function ProductsPage({ onNavigate }: { onNavigate: (page: AppPage) => void }) {
  return <main className="bg-[#f3f5f6]"><section className="bg-[#10293e] text-white"><div className="mx-auto max-w-[1540px] px-5 py-16 lg:px-10 lg:py-20"><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-[#d7aa57]">Gesamtsortiment</p><h1 className="mt-3 max-w-4xl font-display text-5xl font-black tracking-[-.05em] sm:text-6xl">Fünf Bereiche. Eine gemeinsame Projektanfrage.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-white/68">Jede Sparte enthält ausschliesslich die passenden Produkte. Der Kunde gelangt ohne Umweg von der Raumwirkung zur konkreten Referenz und Offerte.</p></div></section><section className="mx-auto max-w-[1540px] space-y-7 px-5 py-12 lg:px-10 lg:py-16">{areas.map((area, index) => <button key={area.page} onClick={() => onNavigate(area.page)} className="group grid w-full overflow-hidden border border-[#d7e0e5] bg-white text-left lg:grid-cols-2"><div className={`min-h-[320px] overflow-hidden bg-[#e9edef] ${index % 2 ? 'lg:order-2' : ''}`}><SmartImage asset={{ src: area.image, alt: area.alt, fit: area.page === 'construction' ? 'contain' : 'cover' }} className={`h-full w-full transition duration-700 group-hover:scale-[1.025] ${area.page === 'construction' ? 'bg-white p-10' : ''}`} /></div><div className={`flex flex-col justify-center p-7 sm:p-10 lg:p-12 ${index % 2 ? 'lg:order-1' : ''}`}><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-[#9a6e22]">Sparte {area.number}</p><div className="mt-3 flex items-start justify-between gap-5"><h2 className="font-display text-4xl font-black tracking-[-.035em] text-[#10293e]">{area.title}</h2><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-[#eef3f6] text-[#004b87] transition group-hover:translate-x-1"><ArrowRight size={19} /></span></div><p className="mt-4 max-w-xl text-base leading-7 text-[#5a707e]">{area.copy}</p></div></button>)}</section><ProcessSteps /></main>;
}
