import { constructionCategories, interiorCategories as sourceCategories } from './data';
import type { InteriorCategory, InteriorProduct } from './types';

export { constructionCategories };

const source = (name: string) => sourceCategories.find((category) => category.germanTitle === name)?.products ?? [];
const porcelain = source('Feinsteinzeug');
const mosaics = source('Premium Mosaike');
const floors = source('SPC / Vinyl-Designböden');
const bathroom = source('Sanitäre Individuallösungen');

const product = (value: InteriorProduct): InteriorProduct => value;

const ceramicAdditions: InteriorProduct[] = [
  product({ id: 'rubicer-techstone-white', name: 'TechStone White', spec: '60×120 cm · matt · rektifiziert · V3', details: 'Ruhige, architektonische Steinoberfläche aus dem Rubicer-Porzellankatalog 2026. Geeignet für hochwertige Wohnräume, Küchen und Bäder.', image: '/images/categories/recer-pixstone-room.webp', brand: 'Rubicer', reference: 'RTC60120WHI', format: '600×1200 mm · 8,5 mm', finish: 'Matt · rektifiziert · V3', application: 'Boden & Wand · Innen/Aussen', box: '2 Platten · 1,44 m² · 27,5 kg', pallet: '32 Kartons · 46,08 m² · ca. 900 kg', badges: ['Architektur', 'Frostbeständig'], featured: true }),
  product({ id: 'rubicer-techstone-cubo', name: 'TechStone White Cubo 3D', spec: '60×120 cm · dreidimensionale Reliefoberfläche', details: 'Skulpturale Wandplatte für reduzierte Luxusinterieurs, Empfang, Bad und repräsentative Akzentwände.', image: '/images/catalog/rubicer-toscana.png', brand: 'Rubicer', reference: 'RTC60120WHICUB', format: '600×1200 mm · 8,5 mm', finish: 'Matt · 3D-Relief', application: 'Wand · Innenbereich', box: '2 Platten · 1,44 m²', pallet: 'Projektbezogene Menge', badges: ['3D Relief', 'Designwand'] }),
  product({ id: 'rubicer-calacata-supremo', name: 'Calacata Supremo', spec: '60×120 cm · poliert · Calacatta-Marmoroptik', details: 'Repräsentative helle Marmoroberfläche für Villen, Hotels, hochwertige Bäder und grosszügige Wohnbereiche.', image: '/images/premium/signature-gold.svg', brand: 'Rubicer', reference: 'Calacata Supremo · Rubicer 2026', format: '600×1200 mm', finish: 'Poliert · rektifiziert', application: 'Boden & Wand · Innenbereich', box: 'Herstellerverpackung gemäss Referenz', pallet: 'Projektbezogene Menge', badges: ['Luxury Marble', 'High Gloss'] }),
  product({ id: 'rubicer-armani-oro-bianco', name: 'Armani Oro Bianco', spec: 'Grossformat · Baby Satin / matt', details: 'Elegante, zurückhaltende Marmorinterpretation mit warmer Goldader für Schweizer Luxusprojekte ohne überladene Wirkung.', image: '/images/premium/signature-gold.svg', brand: 'Rubicer', reference: 'Armani Oro Bianco · Rubicer 2026', format: 'Grossformat gemäss Referenz', finish: 'Baby Satin oder matt', application: 'Boden & Wand · Innenbereich', box: 'Herstellerverpackung', pallet: 'Projektbezogene Menge', badges: ['Warm Luxury', 'Swiss Selection'] }),
  product({ id: 'recer-bluenza-earth-clay', name: 'Bluenza Earth Clay', spec: '120×60R · 60×60R · koordinierte Ripple-Wandplatte', details: 'Warme Natursteinserie mit True-Look-Oberfläche. Ideal für Spa-Bäder, Wohnbereiche und durchgehende In-&-Out-Konzepte.', image: '/images/catalog/recer-bluenza.png', brand: 'Recer', reference: 'Bluenza Earth Clay · Recer 2026', format: '120×60 / 60×60 / 30×60 cm', finish: 'Natural · V4 · R10/B', application: 'Boden & Wand · Innen/Aussen', box: 'Formatabhängig', pallet: 'Formatabhängig', badges: ['True Look', 'In & Out'] }),
  product({ id: 'gresco-majestic', name: 'Majestic', spec: 'Marmor- und Natursteinwirkung · Projektserie', details: 'Aus dem Gresco-Katalog ausgewählte, elegante Oberfläche für repräsentative Innenräume und koordinierte Wand-/Bodenlösungen.', image: '/images/catalog/recer-mastery.png', brand: 'Gresco', reference: 'Majestic · Gresco Katalog', format: 'Formate gemäss Herstellerreferenz', finish: 'Matt oder poliert je Referenz', application: 'Boden & Wand', box: 'Referenzabhängig', pallet: 'Projektbezogene Menge', badges: ['Project Luxury', 'Curated'] }),
];

const selectedMosaics = mosaics.filter((item) => ['recer-mastery-mix', 'recer-bluenza-mosaic'].includes(item.id));

const bathroomAdditions: InteriorProduct[] = [
  product({ id: 'rubicer-stria-horizontal', name: 'Stria Horizontal Waschtischmöbel', spec: '80–160 cm · strukturierte Front · Solid Surface', details: 'Horizontale Designvariante aus dem Rubicer-Möbelkatalog 2026 für ruhige, breite Waschtischlösungen.', image: '/images/catalog/rubicer-stria.png', brand: 'Rubicer', reference: 'Stria Horizontal · Rubicer 2026', format: '80–160 cm', finish: 'Natural Oak, Walnut oder Mattlack', application: 'Badmöbel · Wandmontage', box: '1 Möbelset', pallet: 'Projektbezogene Stückzahl', badges: ['Solid Surface', 'Made in Europe'] }),
  product({ id: 'rubicer-focus-oak', name: 'Focus Oak', spec: 'Badmöbel mit Solid-Surface- und Holzkomposition', details: 'Warme Eichenlösung für elegante Schweizer Bäder mit natürlicher Materialwirkung und klarer Linienführung.', image: '/images/catalog/rubicer-stria.png', brand: 'Rubicer', reference: 'Focus Oak · Rubicer 2026', format: 'Abmessungen gemäss Ausführung', finish: 'Oak · Solid Surface', application: 'Waschtischmöbel', box: '1 Möbelset', pallet: 'Projektbezogene Stückzahl', badges: ['Natural Oak', 'Luxury Bathroom'] }),
  product({ id: 'roca-targa-everlux', name: 'Targa Everlux', spec: 'Waschtisch- und Duscharmaturen · PVD-Finishes', details: 'Roca-Targa-Programm mit langlebigen Everlux-Oberflächen in Gold, gebürstetem Graphit und weiteren hochwertigen Ausführungen.', image: '/images/premium/ramon-soler.svg', brand: 'Roca', reference: 'Targa · Roca Armaturen 2026', format: 'Waschtisch, Dusche, Badewanne, Unterputz', finish: 'Chrom, Schwarz matt, Weiss matt, Gold, Graphit', application: 'Armaturenprogramm', box: '1 Stück / Set', pallet: 'Projektbezogene Stückzahl', badges: ['Everlux PVD', 'Roca 2026'], featured: true }),
  product({ id: 'moovlux-tube-gold', name: 'Tube Gold Unterputz-Set', spec: 'Unterputz-Waschtisch- oder Duschlösung · Gold', details: 'Minimalistische Tube-Geometrie mit Easy-Box-System und hochwertigem Goldfinish aus dem Moovlux-Katalog.', image: '/images/products/moovlux-tube-tl1001.webp', imageFit: 'contain', brand: 'Moovlux', reference: 'EP1037 / EP1040 / Tube Gold', format: 'Unterputzsystem', finish: 'Gold', application: 'Waschtisch oder Dusche', box: '1 Komplettset', pallet: 'Projektbezogene Stückzahl', badges: ['Unterputz', 'Gold Finish'] }),
  product({ id: 'roca-line-plus', name: 'Line Plus Duschabtrennung', spec: 'Walk-in, Schiebe- und Ecklösungen', details: 'Hochwertige Glaslösung aus dem Roca-Divisórias-Katalog für grosszügige Walk-in-Duschen und präzise Projektplanung.', image: '/images/premium/roca-screens.svg', brand: 'Roca', reference: 'Line Plus · Roca Divisórias 2025', format: 'Mass- und modellabhängig', finish: 'Klarglas · Profil gemäss Ausführung', application: 'Duschabtrennung', box: '1 System', pallet: 'Projektbezogene Lieferung', badges: ['Walk-in', 'Roca Glass'] }),
  product({ id: 'rubicer-fly-cappuccino', name: 'Fly BTW Cappuccino Matt', spec: 'Rimless · Easy Clean · Soft Close', details: 'Farbige, wandnahe WC-Lösung aus der Rubicer Color Collection für warme, tonale Badezimmerkonzepte.', image: '/images/products/roca-avant-intank.webp', imageFit: 'contain', brand: 'Rubicer', reference: 'RSA2342XMC', format: 'Back-to-wall WC', finish: 'Cappuccino matt', application: 'WC · Bodenmontage', box: '1 WC-Pack', pallet: 'Projektbezogene Stückzahl', badges: ['Rimless', 'Cappuccino Matt'] }),
  product({ id: 'rubicer-elegant-black', name: 'Elegant Black WC', spec: 'Rimless · Soft Close · Schwarz matt', details: 'Reduzierte schwarze Sanitärlösung für kontrastreiche Luxusbadkonzepte und hochwertige Hotelbäder.', image: '/images/products/roca-avant-intank.webp', imageFit: 'contain', brand: 'Rubicer', reference: 'Elegant Black · Rubicer 2026', format: 'BTW oder wandhängend je Ausführung', finish: 'Schwarz matt', application: 'WC', box: '1 WC-Pack', pallet: 'Projektbezogene Stückzahl', badges: ['Black Edition', 'Rimless'] }),
];

const floorAdditions: InteriorProduct[] = [
  product({ id: 'rubifloor-herringbone-dark', name: 'Herringbone Dark EIR', spec: 'Fischgrat · 6/0,55 mm · integrierte Unterlage', details: 'Dunklere, elegante Fischgratvariante für Bibliothek, Lounge, Boutique und charaktervolle Wohnräume.', image: '/images/products/rubifloor-herringbone-natural.webp', brand: 'Rubifloor', reference: 'Herringbone Dark · Rubicer SPC', format: '142×710 mm', finish: 'EIR · 0,55 mm Nutzschicht', application: 'High Traffic & Residential', box: 'Herstellerverpackung', pallet: 'Projektbezogene Menge', badges: ['Fischgrat', 'Dark Oak'] }),
  product({ id: 'rubifloor-xl-city', name: 'XL1.8 City EIR', spec: '23×182 cm · extralange Diele', details: 'Ruhiger urbaner Eichenlook für grosszügige Apartments und hochwertige Renovationen.', image: '/images/products/rubifloor-xl-home.webp', brand: 'Rubifloor', reference: 'XL1.8 City · Rubicer SPC', format: '230×1820 mm', finish: 'EIR · integrierte Unterlage', application: 'Wohn- und Objektbereich', box: 'Herstellerverpackung', pallet: 'Projektbezogene Menge', badges: ['XL Plank', 'Urban Oak'] }),
  product({ id: 'rubifloor-premium-milk', name: 'Premium Milk EIR', spec: '18×153 cm · helle Eiche · 0,55 mm Nutzschicht', details: 'Sehr helle, ruhige Holzoptik für minimalistische Schweizer Innenräume und hochwertige Mietobjekte.', image: '/images/products/rubifloor-premium-cream.webp', brand: 'Rubifloor', reference: 'Premium Milk · Rubicer SPC', format: '180×1530 mm', finish: 'EIR · 0,55 mm Nutzschicht', application: 'High Traffic & Residential', box: 'Herstellerverpackung', pallet: 'Projektbezogene Menge', badges: ['Light Oak', 'Premium'] }),
  product({ id: 'rubifloor-alpha-camel', name: 'Alpha Camel EIR', spec: 'Warme Eiche · EIR-Struktur', details: 'Ausgewogene Camel-Eiche für Wohnbereiche, Schlafzimmer und Hospitality-Projekte mit natürlicher Farbtemperatur.', image: '/images/products/rubifloor-pro-nordig.webp', brand: 'Rubifloor', reference: 'Alpha Camel · Rubicer SPC', format: 'Gemäss Herstellerreferenz', finish: 'EIR', application: 'Wohn- und Objektbereich', box: 'Herstellerverpackung', pallet: 'Projektbezogene Menge', badges: ['Warm Oak', 'EIR'] }),
  product({ id: 'corkart-vinyl-contract', name: 'Vinyl Concept Contract', spec: 'Glue-down oder Click · wasserbeständig', details: 'Corkart-Vertragskollektion mit hoher Leistung, Designauswahl und Systemen für anspruchsvolle Wohn- und Objektanwendungen.', image: '/images/products/rubifloor-xl-home.webp', brand: 'Corkart', reference: 'Vinyl Concept · Contract Collection', format: 'System- und dekorspezifisch', finish: 'PU-Finish · Designfilm', application: 'Wohnung, Hotel, Büro, Retail', box: 'Referenzabhängig', pallet: 'Projektbezogene Menge', badges: ['Contract', 'Water Resistant'] }),
  product({ id: 'corkart-natural-cork', name: 'Natural Cork Comfort', spec: 'Floating oder Glue-down · thermisch und akustisch', details: 'Natürlicher Korkboden mit warmer Haptik, Trittschallkomfort und hoher Elastizität für Schlafzimmer, Suiten und ruhige Wohnräume.', image: '/images/products/rubifloor-premium-cream.webp', brand: 'Corkart', reference: 'Cork Concept · Contract Collection', format: '900×300 mm je System', finish: 'Natural Shield Wax oder Ultra Shield', application: 'Wohnung, Hotelzimmer, Wellness', box: 'Systemabhängig', pallet: 'Projektbezogene Menge', badges: ['Natural Cork', 'Acoustic Comfort'] }),
];

const concepts: InteriorProduct[] = [
  product({ id: 'concept-warm-stone-spa', name: 'Warm Stone Spa Bathroom', spec: 'Bluenza Earth Clay · Stria Oak · Gold Armaturen', details: 'Komplettes warmes Spa-Konzept mit Recer-Bluenza-Flächen, ausgewähltem Mosaik, Rubicer-Stria-Möbel, Goldarmatur, Slim-Duschwanne und Walk-in-Glas.', image: '/images/catalog/recer-bluenza.png', brand: 'Raumkonzept', reference: 'Konzept 01 · projektbezogene Visualisierung', format: 'Komplettbad', finish: 'Warm Stone · Natural Oak · Gold', application: 'Masterbad · Spa · Hotel Suite', box: 'Produkte einzeln wählbar', pallet: 'Komplettlieferung nach Projekt', badges: ['Komplettbad', 'Swiss Luxury'], featured: true }),
  product({ id: 'concept-marble-gold', name: 'Marble & Gold Suite', spec: 'Signature Gold · Targa Everlux · Walk-in Glas', details: 'Repräsentatives Badkonzept mit goldgeädertem Feinsteinzeug, warmen Metalloberflächen, klarer Glasarchitektur und reduzierter Sanitärtechnik.', image: '/images/premium/signature-gold.svg', brand: 'Raumkonzept', reference: 'Konzept 02 · projektbezogene Visualisierung', format: 'Komplettbad', finish: 'Marmor Weiss/Gold', application: 'Villa · Penthouse · Boutique Hotel', box: 'Produkte einzeln wählbar', pallet: 'Komplettlieferung nach Projekt', badges: ['Marble', 'Gold Finish'] }),
  product({ id: 'concept-soft-minimal', name: 'Soft Minimal Bathroom', spec: 'TechStone White · Natural Oak · Chrom', details: 'Helles, zeitloses Konzept für Schweizer Neubau und hochwertige Renovation. Ruhige Steinfläche, Eichenmöbel, präzise Chromarmaturen und bodengleiche Dusche.', image: '/images/catalog/rubicer-stria.png', brand: 'Raumkonzept', reference: 'Konzept 03 · projektbezogene Visualisierung', format: 'Komplettbad', finish: 'Off White · Oak · Chrome', application: 'Wohnung · Neubau · Renovation', box: 'Produkte einzeln wählbar', pallet: 'Komplettlieferung nach Projekt', badges: ['Timeless', 'Natural Oak'] }),
  product({ id: 'concept-dark-spa', name: 'Dark Architectural Spa', spec: 'Bluenza Ebony · Black WC · Graphit Armaturen', details: 'Dunkles Architekturkonzept mit kräftiger Steinwirkung, schwarzen Sanitärteilen, Graphitarmaturen und grosszügiger Walk-in-Dusche.', image: '/images/premium/roca-screens.svg', brand: 'Raumkonzept', reference: 'Konzept 04 · projektbezogene Visualisierung', format: 'Komplettbad', finish: 'Ebony · Black · Graphite', application: 'Spa · Hotel · Statement Bathroom', box: 'Produkte einzeln wählbar', pallet: 'Komplettlieferung nach Projekt', badges: ['Dark Spa', 'Architectural'] }),
  product({ id: 'concept-herringbone-living', name: 'Natural Herringbone Living', spec: 'Herringbone Natural · warme neutrale Wände', details: 'Wohnkonzept für elegante Apartments und Altbaurenovationen mit natürlichem Fischgratboden und ruhiger, hochwertiger Materialpalette.', image: '/images/products/rubifloor-herringbone-natural.webp', brand: 'Raumkonzept', reference: 'Konzept 05 · projektbezogene Visualisierung', format: 'Wohnraumkonzept', finish: 'Natural Oak', application: 'Wohnzimmer · Esszimmer · Apartment', box: 'Boden und Ergänzungen einzeln wählbar', pallet: 'Projektbezogene Lieferung', badges: ['Herringbone', 'Living'] }),
  product({ id: 'concept-concrete-oak-kitchen', name: 'Concrete & Oak Kitchen', spec: 'TechStone Grey · XL City EIR', details: 'Reduziertes Küchen- und Essraumkonzept mit mineralischer Keramikoberfläche und grosszügiger Eichenoptik für moderne Schweizer Innenräume.', image: '/images/products/rubifloor-xl-home.webp', brand: 'Raumkonzept', reference: 'Konzept 06 · projektbezogene Visualisierung', format: 'Küchen- und Essraumkonzept', finish: 'Concrete Grey · Oak', application: 'Küche · Essen · Open Space', box: 'Produkte einzeln wählbar', pallet: 'Projektbezogene Lieferung', badges: ['Kitchen', 'Open Space'] }),
];

export const interiorCategories: InteriorCategory[] = [
  {
    title: 'Ceramic & Porcelain',
    germanTitle: 'Keramik & Feinsteinzeug',
    description: 'Kuratiertes Feinsteinzeug, Wandkeramik und ausgewählte koordinierte Mosaike aus den vier Hersteller-ZIP-Katalogen – für den Schweizer Premium- und Luxusmarkt.',
    products: [...porcelain, ...ceramicAdditions, ...selectedMosaics],
  },
  {
    title: 'Bathroom',
    germanTitle: 'Badezimmer',
    description: 'Hochwertige Möbel, Armaturen, Duschsysteme, Glas, WCs und Duschwannen von Rubicer, Roca, Moovlux und IMEX.',
    products: [...bathroom, ...bathroomAdditions],
  },
  {
    title: 'Vinyl, SPC & Cork',
    germanTitle: 'Vinyl, SPC & Kork',
    description: 'Premium-SPC, Vinyl- und Korklösungen für hochwertige Wohnungen, Hotels, Büros und Renovationen.',
    products: [...floors, ...floorAdditions],
  },
  {
    title: 'Complete Room Concepts',
    germanTitle: 'Raumkonzepte',
    description: 'Kuratierten Produktkombinationen als Inspiration: komplette Bäder, Wohnräume und Küchen. Jedes Produkt bleibt einzeln wählbar und projektbezogen bestätigbar.',
    products: concepts,
  },
];
